---
- name: Prepare for PostgreSQL
  hosts: db
  become: true
  roles:
    - role: adfinis_sygroup.grub
      grub_console: False
      grub_consoles: []
      grub_serial: []
      grub_timeout: 0
      grub_disable_network_predictable_interface_names: False
      grub_cmdline_linux_default_list:
        - maybe-ubiquity
        - transparent_hugepage=never
      tags:
        - no_testing
        
  post_tasks:
    - name: Add PostgreSQL yum repository
      include_tasks: tasks/add_postgresql_yum_repo.yml

    - name: Install PostgreSQL server
      package:
        name: postgresql93-server

- name: Initialize PostgreSQL cluster
  hosts: db
  become: true
  become_user: postgres
  gather_facts: false
  tasks:
    - name: Initialize
      shell: |
        # TODO - This only checks for the existence of the database. It should be modified to
        # check whether or not the correct collate value is set.
        if ! [ -e /var/lib/pgsql/9.3/data/PG_VERSION ]
        then
          /usr/pgsql-9.3/bin/initdb --auth ident \
                                    --lc-collate C \
                                    --locale en_US.UTF-8 \
                                    --pgdata /var/lib/pgsql/9.3/data

          if [ "$?" -ne 0 ]
          then
            exit 1
          fi

          printf 'changed'
        fi
      register: result
      changed_when: result.stdout == 'changed'
  tags:
    - no_testing
