- hosts: all
  become: yes 
  tasks:

  # Start docker
  # Docker is already installed on vms, we need to only enable them
  # OR manually: 
  # systemctl start docker
  # systemctl enable docker
  # systemctl status docker
   - name: start & enable Docker
     service:
       name: docker
       state: started # systemctl start docker
       enabled: yes   # systemctl enable docker
